### ISSUE TITLE
Can't install dotenv

### ISSUE THREAD

**Issue by wolvez7** [alexbobes/bitcoin-brute-force-tool#1]
Collecting dotenv
  Downloading dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [78 lines of output]
      C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
        error: subprocess-exited-with-error

        python setup.py egg_info did not run successfully.
        exit code: 1

        [16 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 14, in <module>
          File "C:\Users\Administrator\AppData\Local\Temp\pip-wheel-p548flgz\distribute_b62e5c6d2d384cc7a0106d8aa87e32bf\setuptools\__init__.py", line 2, in <module>
            from setuptools.extension import Extension, Library
          File "C:\Users\Administrator\AppData\Local\Temp\pip-wheel-p548flgz\distribute_b62e5c6d2d384cc7a0106d8aa87e32bf\setuptools\extension.py", line 5, in <module>
            from setuptools.dist import _get_unpatched
          File "C:\Users\Administrator\AppData\Local\Temp\pip-wheel-p548flgz\distribute_b62e5c6d2d384cc7a0106d8aa87e32bf\setuptools\dist.py", line 7, in <module>
            from setuptools.command.install import install
          File "C:\Users\Administrator\AppData\Local\Temp\pip-wheel-p548flgz\distribute_b62e5c6d2d384cc7a0106d8aa87e32bf\setuptools\command\__init__.py", line 8, in <module>
            from setuptools.command import install_scripts
          File "C:\Users\Administrator\AppData\Local\Temp\pip-wheel-p548flgz\distribute_b62e5c6d2d384cc7a0106d8aa87e32bf\setuptools\command\install_scripts.py", line 3, in <module>
            from pkg_resources import Distribution, PathMetadata, ensure_directory
          File "C:\Users\Administrator\AppData\Local\Temp\pip-wheel-p548flgz\distribute_b62e5c6d2d384cc7a0106d8aa87e32bf\pkg_resources.py", line 1518, in <module>
            register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
        AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed

      Encountered error while generating package metadata.

      See above for output.

      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp0t3cr1fb', '--quiet', 'distribute']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-o1lzompw\dotenv_c086b0d80d8e4bacb6d85b3057cdd8e0\setup.py", line 13, in <module>
          setup(name='dotenv',
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 674, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\pkg_resources\__init__.py", line 1147, in obtain
          return installer(requirement)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp0t3cr1fb', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by alexbobes** [comment]
Try installing **python-dotenv** instead of **dotenv**: **pip install python-dotenv**
